base_url = "/"
title = "Dot UI"
compile_sass = false
build_search_index = false


[extra]
description = "Semantic UI components - no framework required."
version = "0.2.1-beta"


[markdown]
highlighting = {
    theme = "catppuccin-mocha"
}