base_url = "https://usedot.dev"
title = "Dot UI"
compile_sass = false
build_search_index = false


[extra]
description = "dot-ui is a lightweight UI component library built on semantic HTML elements. No framework, no dependencies - drop in two tags and start building."
version = "0.2.1-beta"
web = "https://usedot.dev"

[markdown]
highlighting = {
    theme = "catppuccin-mocha"
}