name: Deploy Zola site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: make css

      - name: Build JS
        run: make js

      - name: Build and deploy Zola
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          BUILD_DIR: docs
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}