name: Deploy Zola site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          BUILD_DIR: docs
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}